import type { AgentType, AgentEvent } from "./types";

export const AGENT_CONFIG: Record<
  AgentType,
  { label: string; iconName: string; color: string; bgColor: string }
> = {
  vob: {
    label: "VOB Agent",
    iconName: "ShieldCheck",
    color: "text-blue-600 dark:text-blue-400",
    bgColor: "bg-blue-500",
  },
  placement: {
    label: "Placement Agent",
    iconName: "MapPin",
    color: "text-purple-600 dark:text-purple-400",
    bgColor: "bg-purple-500",
  },
  risk: {
    label: "Risk Agent",
    iconName: "AlertTriangle",
    color: "text-amber-600 dark:text-amber-400",
    bgColor: "bg-amber-500",
  },
  triage: {
    label: "Triage Agent",
    iconName: "ListOrdered",
    color: "text-green-600 dark:text-green-400",
    bgColor: "bg-green-500",
  },
};

// Pre-authored events that reference real mock-data IDs
export const AGENT_EVENT_POOL: Omit<AgentEvent, "id" | "timestamp">[] = [
  // VOB Agent events
  {
    agent: "vob",
    action: "Querying EDI 270/271 for eligibility",
    targetId: "VOB-1847",
    targetLabel: "M.R. — BCBS",
    status: "processing",
    centerId: "PHL",
  },
  {
    agent: "vob",
    action: "Eligibility confirmed — extracting MH/SUD benefits",
    targetId: "VOB-1847",
    targetLabel: "M.R. — BCBS",
    status: "complete",
    result: "In-network, $250 deductible remaining",
    centerId: "PHL",
  },
  {
    agent: "vob",
    action: "Parsing Aetna benefit schedule for SUD coverage",
    targetId: "VOB-1846",
    targetLabel: "K.L. — Aetna",
    status: "processing",
    centerId: "DEV",
  },
  {
    agent: "vob",
    action: "Benefits extracted — 30-day residential authorized",
    targetId: "VOB-1846",
    targetLabel: "K.L. — Aetna",
    status: "complete",
    result: "90% covered after $500 deductible",
    centerId: "DEV",
  },
  {
    agent: "vob",
    action: "Submitting prior auth notification to Anthem",
    targetId: "VOB-1841",
    targetLabel: "N.W. — Anthem",
    status: "processing",
    centerId: "MAY",
  },
  {
    agent: "vob",
    action: "Prior auth approved — routing to center matching",
    targetId: "VOB-1841",
    targetLabel: "N.W. — Anthem",
    status: "complete",
    result: "Auth #ANT-882491 valid 30 days",
    centerId: "MAY",
  },
  {
    agent: "vob",
    action: "Checking Medicaid PA coverage for residential SUD",
    targetId: "VOB-1845",
    targetLabel: "T.J. — Medicaid PA",
    status: "processing",
    centerId: "WES",
  },
  {
    agent: "vob",
    action: "Coverage gap detected — needs manual review",
    targetId: "VOB-1845",
    targetLabel: "T.J. — Medicaid PA",
    status: "warning",
    result: "PA Medicaid requires ASAM Level 3.7 documentation",
    centerId: "WES",
  },

  // Placement Agent events
  {
    agent: "placement",
    action: "Scoring centers for detox + residential placement",
    targetId: "REF-3201",
    targetLabel: "M.R. — ER Transfer",
    status: "processing",
    centerId: "PHL",
  },
  {
    agent: "placement",
    action: "Top match: Philadelphia (3 beds, BCBS in-network)",
    targetId: "REF-3201",
    targetLabel: "M.R. — ER Transfer",
    status: "complete",
    result: "PHL 92% match, DAN 78%, DEV 71%",
    centerId: "PHL",
  },
  {
    agent: "placement",
    action: "Evaluating center availability for court-mandated placement",
    targetId: "REF-3194",
    targetLabel: "S.M. — Drug Court",
    status: "processing",
    centerId: "MAY",
  },
  {
    agent: "placement",
    action: "Mays Landing: 1 bed, Medicaid NJ accepted — 72hr deadline flagged",
    targetId: "REF-3194",
    targetLabel: "S.M. — Drug Court",
    status: "warning",
    result: "Only 1 bed at nearest center — escalate",
    centerId: "MAY",
  },
  {
    agent: "placement",
    action: "Running insurance-program-bed match for Anthem",
    targetId: "REF-3195",
    targetLabel: "N.W. — ER Transfer",
    status: "processing",
    centerId: "MAY",
  },
  {
    agent: "placement",
    action: "Matched: Mays Landing residential (Anthem in-network)",
    targetId: "REF-3195",
    targetLabel: "N.W. — ER Transfer",
    status: "complete",
    result: "MAY best fit — detox bed available",
    centerId: "MAY",
  },

  // Risk Agent events
  {
    agent: "risk",
    action: "Calculating drop-off risk — ER transfer, 75min elapsed",
    targetId: "REF-3201",
    targetLabel: "M.R.",
    status: "processing",
    centerId: "PHL",
  },
  {
    agent: "risk",
    action: "Risk score: 72/100 — high (elapsed time + ER source)",
    targetId: "REF-3201",
    targetLabel: "M.R.",
    status: "warning",
    result: "Action needed within 2 hours",
    centerId: "PHL",
  },
  {
    agent: "risk",
    action: "Assessing retention factors for court-mandated referral",
    targetId: "REF-3194",
    targetLabel: "S.M.",
    status: "processing",
    centerId: "MAY",
  },
  {
    agent: "risk",
    action: "Risk score: 45/100 — moderate (court mandate reduces flight risk)",
    targetId: "REF-3194",
    targetLabel: "S.M.",
    status: "complete",
    result: "Deadline pressure offset by mandate compliance",
    centerId: "MAY",
  },
  {
    agent: "risk",
    action: "Monitoring 988 crisis referral — no callback yet",
    targetId: "REF-3193",
    targetLabel: "B.T.",
    status: "warning",
    result: "15min since transfer — escalate to triage",
  },
  {
    agent: "risk",
    action: "Risk score: 28/100 — low (family support, scheduled screening)",
    targetId: "REF-3192",
    targetLabel: "L.H.",
    status: "complete",
    result: "Stable — screening at 3pm today",
    centerId: "IND",
  },

  // Triage Agent events
  {
    agent: "triage",
    action: "Re-prioritizing queue — 3 ER transfers in pipeline",
    targetId: "QUEUE",
    targetLabel: "Active Queue",
    status: "processing",
  },
  {
    agent: "triage",
    action: "Queue reordered: REF-3193 (crisis) → REF-3201 (ER) → REF-3195 (ER)",
    targetId: "QUEUE",
    targetLabel: "Active Queue",
    status: "complete",
    result: "988 crisis elevated to position #1",
  },
  {
    agent: "triage",
    action: "Flagging unassigned high-priority referrals",
    targetId: "REF-3193",
    targetLabel: "B.T. — 988 Crisis",
    status: "warning",
    result: "No BDO assigned — needs immediate attention",
  },
  {
    agent: "triage",
    action: "Analyzing BDO workload — Marcus W. at capacity (3 active)",
    targetId: "BDO-LOAD",
    targetLabel: "BDO Workload",
    status: "processing",
  },
  {
    agent: "triage",
    action: "Recommending Derek S. for next ER referral assignment",
    targetId: "BDO-LOAD",
    targetLabel: "BDO Workload",
    status: "complete",
    result: "Derek S. has 1 active referral — capacity available",
  },
  {
    agent: "triage",
    action: "Savannah center at 100% — blocking new placements",
    targetId: "SAV",
    targetLabel: "Savannah, GA",
    status: "warning",
    result: "0 beds available — redirect to Tampa or Raleigh",
    centerId: "SAV",
  },
];
