import type {
  KPI,
  FunnelStage,
  VOBRecord,
  Center,
  Referral,
  TimeSeriesPoint,
} from "./types";

// KPIs derived from interview data + industry benchmarks
// Sarah Chen: 60% BDO-sourced, target 75%
// Funnel benchmarks: 2.4% lead-to-admit, 15.9% lead-to-VOB
// VOB: 43% viability rate, manual 30-60 min
export const kpis: KPI[] = [
  { label: "Monthly Inquiries", value: 2840, unit: "", change: 8.2, trend: "up", good: "up" },
  { label: "VOB Turnaround", value: 47, unit: "min avg", change: -12, trend: "down", good: "down" },
  { label: "Conversion Rate", value: 2.1, unit: "%", change: 0.3, trend: "up", good: "up" },
  { label: "Beds Available", value: 34, unit: "of 412", change: -8, trend: "down", good: "up" },
  { label: "BDO-Sourced", value: 61, unit: "%", change: 2, trend: "up", good: "up" },
  { label: "Avg Time-to-Admit", value: 22, unit: "hours", change: -3, trend: "down", good: "down" },
];

// Funnel: industry benchmarks from admissions-funnel-benchmarks.md
export const funnel: FunnelStage[] = [
  { stage: "Inquiries", count: 2840, rate: 100 },
  { stage: "Screened", count: 1704, rate: 60 },
  { stage: "VOB Started", count: 452, rate: 15.9 },
  { stage: "VOB Viable", count: 194, rate: 6.8 },
  { stage: "Admitted", count: 60, rate: 2.1 },
];

// VOB records — reflects Treatment Specialist interview:
// Manual process via Salesforce + insurer portals, 30 min to "a day or more" (Team Lead)
// Priority from BDO referrals is informal, not structural
export const vobRecords: VOBRecord[] = [
  {
    id: "VOB-1847",
    patientInitials: "M.R.",
    insurance: "Blue Cross Blue Shield",
    insuranceType: "commercial",
    status: "in_progress",
    submittedAt: "2026-03-25T13:15:00",
    completedAt: null,
    assignedTo: "Jessica T.",
    center: "Philadelphia",
    elapsedMin: 75,
    priority: "high",
    referralSource: "ER — Jefferson Hospital",
  },
  {
    id: "VOB-1846",
    patientInitials: "K.L.",
    insurance: "Aetna",
    insuranceType: "commercial",
    status: "pending",
    submittedAt: "2026-03-25T12:40:00",
    completedAt: null,
    assignedTo: "Unassigned",
    center: "Devon",
    elapsedMin: 110,
    priority: "high",
    referralSource: "BDO — Marcus W.",
  },
  {
    id: "VOB-1845",
    patientInitials: "T.J.",
    insurance: "Medicaid PA",
    insuranceType: "medicaid",
    status: "needs_review",
    submittedAt: "2026-03-25T11:20:00",
    completedAt: null,
    assignedTo: "Sarah M.",
    center: "Westminster",
    elapsedMin: 190,
    priority: "medium",
    referralSource: "Self-referral",
  },
  {
    id: "VOB-1844",
    patientInitials: "A.P.",
    insurance: "United Healthcare",
    insuranceType: "commercial",
    status: "verified",
    submittedAt: "2026-03-25T09:45:00",
    completedAt: "2026-03-25T10:22:00",
    assignedTo: "Jessica T.",
    center: "Danvers",
    elapsedMin: 37,
    priority: "medium",
    referralSource: "BDO — Lisa K.",
  },
  {
    id: "VOB-1843",
    patientInitials: "R.S.",
    insurance: "Cigna",
    insuranceType: "commercial",
    status: "verified",
    submittedAt: "2026-03-25T08:30:00",
    completedAt: "2026-03-25T09:15:00",
    assignedTo: "David L.",
    center: "Earleville",
    elapsedMin: 45,
    priority: "low",
    referralSource: "Therapist — Dr. Chen",
  },
  {
    id: "VOB-1842",
    patientInitials: "J.D.",
    insurance: "Tricare",
    insuranceType: "tricare",
    status: "denied",
    submittedAt: "2026-03-25T07:10:00",
    completedAt: "2026-03-25T08:50:00",
    assignedTo: "Sarah M.",
    center: "St. Charles",
    elapsedMin: 100,
    priority: "medium",
    referralSource: "VA Liaison",
  },
  {
    id: "VOB-1841",
    patientInitials: "N.W.",
    insurance: "Anthem",
    insuranceType: "commercial",
    status: "in_progress",
    submittedAt: "2026-03-25T13:50:00",
    completedAt: null,
    assignedTo: "David L.",
    center: "Mays Landing",
    elapsedMin: 40,
    priority: "high",
    referralSource: "ER — AtlantiCare",
  },
  {
    id: "VOB-1840",
    patientInitials: "C.B.",
    insurance: "Humana",
    insuranceType: "commercial",
    status: "pending",
    submittedAt: "2026-03-25T14:05:00",
    completedAt: null,
    assignedTo: "Unassigned",
    center: "Indianapolis",
    elapsedMin: 25,
    priority: "low",
    referralSource: "Self-referral",
  },
];

// Centers — 11-center network matching case prompt
// Bed data reflects: Treatment Specialist uses "Excel/PDFs", must call to confirm
// Ops Manager: "center-level variation exists"
export const centers: Center[] = [
  {
    id: "PHL",
    name: "Philadelphia",
    state: "PA",
    region: "northeast",
    totalBeds: 48,
    beds: { available: 3, occupied: 40, reserved: 3, maintenance: 2 },
    programs: ["Detox", "Residential", "PHP"],
    coordinates: [-75.1652, 39.9526],
    acceptedInsurance: ["BCBS", "Aetna", "UHC", "Cigna", "Medicaid PA", "Medicare"],
  },
  {
    id: "DEV",
    name: "Devon",
    state: "PA",
    region: "northeast",
    totalBeds: 42,
    beds: { available: 5, occupied: 33, reserved: 2, maintenance: 2 },
    programs: ["Residential", "PHP", "IOP"],
    coordinates: [-75.4271, 40.0487],
    acceptedInsurance: ["BCBS", "Aetna", "UHC", "Anthem", "Cigna"],
  },
  {
    id: "WES",
    name: "Westminster",
    state: "MD",
    region: "northeast",
    totalBeds: 40,
    beds: { available: 2, occupied: 35, reserved: 2, maintenance: 1 },
    programs: ["Detox", "Residential"],
    coordinates: [-76.9958, 39.5751],
    acceptedInsurance: ["BCBS", "Aetna", "Medicaid PA", "Medicaid MD", "Cigna"],
  },
  {
    id: "EAR",
    name: "Earleville",
    state: "MD",
    region: "northeast",
    totalBeds: 36,
    beds: { available: 4, occupied: 28, reserved: 3, maintenance: 1 },
    programs: ["Residential", "PHP"],
    coordinates: [-75.9368, 39.4134],
    acceptedInsurance: ["BCBS", "Cigna", "UHC", "Anthem"],
  },
  {
    id: "DAN",
    name: "Danvers",
    state: "MA",
    region: "northeast",
    totalBeds: 38,
    beds: { available: 6, occupied: 29, reserved: 2, maintenance: 1 },
    programs: ["Detox", "Residential", "PHP"],
    coordinates: [-70.9495, 42.5751],
    acceptedInsurance: ["BCBS", "UHC", "Aetna", "Humana", "Medicaid MA"],
  },
  {
    id: "MAY",
    name: "Mays Landing",
    state: "NJ",
    region: "northeast",
    totalBeds: 32,
    beds: { available: 1, occupied: 28, reserved: 2, maintenance: 1 },
    programs: ["Residential", "IOP"],
    coordinates: [-74.7277, 39.4529],
    acceptedInsurance: ["BCBS", "Anthem", "UHC", "Medicaid NJ", "Aetna"],
  },
  {
    id: "STC",
    name: "St. Charles",
    state: "IL",
    region: "midwest",
    totalBeds: 44,
    beds: { available: 7, occupied: 32, reserved: 3, maintenance: 2 },
    programs: ["Detox", "Residential", "PHP", "IOP"],
    coordinates: [-88.3087, 41.9142],
    acceptedInsurance: ["BCBS", "UHC", "Aetna", "Humana", "Tricare", "Medicaid IL"],
  },
  {
    id: "IND",
    name: "Indianapolis",
    state: "IN",
    region: "midwest",
    totalBeds: 36,
    beds: { available: 3, occupied: 30, reserved: 2, maintenance: 1 },
    programs: ["Residential", "PHP"],
    coordinates: [-86.1581, 39.7684],
    acceptedInsurance: ["BCBS", "Anthem", "UHC", "Humana", "Medicaid IN"],
  },
  {
    id: "RAL",
    name: "Raleigh",
    state: "NC",
    region: "southeast",
    totalBeds: 34,
    beds: { available: 2, occupied: 29, reserved: 2, maintenance: 1 },
    programs: ["Detox", "Residential"],
    coordinates: [-78.6382, 35.7796],
    acceptedInsurance: ["BCBS", "Aetna", "UHC", "Cigna", "Medicaid NC"],
  },
  {
    id: "SAV",
    name: "Savannah",
    state: "GA",
    region: "southeast",
    totalBeds: 30,
    beds: { available: 0, occupied: 27, reserved: 2, maintenance: 1 },
    programs: ["Residential", "IOP"],
    coordinates: [-81.0912, 32.0809],
    acceptedInsurance: ["BCBS", "UHC", "Aetna", "Humana"],
  },
  {
    id: "TAM",
    name: "Tampa",
    state: "FL",
    region: "southeast",
    totalBeds: 32,
    beds: { available: 1, occupied: 28, reserved: 2, maintenance: 1 },
    programs: ["Detox", "Residential", "PHP"],
    coordinates: [-82.4572, 27.9506],
    acceptedInsurance: ["BCBS", "UHC", "Aetna", "Humana", "Cigna", "Medicaid FL"],
  },
];

// Referral pipeline — BDO-centric view
// Sarah Chen Q9: BDOs regional, measured on admissions + conversion + cost
// BDO interview: handoff is "warm transfer" but feedback loop is broken (BDO-2)
export const referrals: Referral[] = [
  {
    id: "REF-3201",
    patientInitials: "M.R.",
    source: "Jefferson Hospital ER",
    sourceType: "er",
    bdo: "Marcus W.",
    stage: "vob_started",
    center: "Philadelphia",
    insurance: "BCBS",
    insuranceType: "commercial",
    createdAt: "2026-03-25T12:30:00",
    lastActivity: "2026-03-25T13:15:00",
    notes: "ER transfer request — patient medically stable, requesting detox bed",
    priority: "high",
  },
  {
    id: "REF-3200",
    patientInitials: "K.L.",
    source: "Dr. Patel (PCP)",
    sourceType: "clinician",
    bdo: "Marcus W.",
    stage: "vob_started",
    center: "Devon",
    insurance: "Aetna",
    insuranceType: "commercial",
    createdAt: "2026-03-25T11:00:00",
    lastActivity: "2026-03-25T12:40:00",
    notes: "PCP referral — alcohol use disorder, prior treatment 2024",
    priority: "high",
  },
  {
    id: "REF-3199",
    patientInitials: "T.J.",
    source: "Website inquiry",
    sourceType: "self",
    bdo: "",
    stage: "vob_started",
    center: "Westminster",
    insurance: "Medicaid PA",
    insuranceType: "medicaid",
    createdAt: "2026-03-25T10:15:00",
    lastActivity: "2026-03-25T11:20:00",
    notes: "Self-referral — opioid use, seeking residential",
    priority: "medium",
  },
  {
    id: "REF-3198",
    patientInitials: "A.P.",
    source: "AtlantiCare Behavioral Health",
    sourceType: "clinician",
    bdo: "Lisa K.",
    stage: "admitted",
    center: "Danvers",
    insurance: "UHC",
    insuranceType: "commercial",
    createdAt: "2026-03-24T15:00:00",
    lastActivity: "2026-03-25T10:22:00",
    notes: "VOB verified — admitted this morning",
    priority: "medium",
  },
  {
    id: "REF-3197",
    patientInitials: "R.S.",
    source: "Dr. Chen (Therapist)",
    sourceType: "therapist",
    bdo: "Lisa K.",
    stage: "vob_complete",
    center: "Earleville",
    insurance: "Cigna",
    insuranceType: "commercial",
    createdAt: "2026-03-24T09:30:00",
    lastActivity: "2026-03-25T09:15:00",
    notes: "VOB verified — scheduling transport",
    priority: "low",
  },
  {
    id: "REF-3196",
    patientInitials: "J.D.",
    source: "VA Liaison",
    sourceType: "clinician",
    bdo: "Derek S.",
    stage: "lost",
    center: "St. Charles",
    insurance: "Tricare",
    insuranceType: "tricare",
    createdAt: "2026-03-23T14:00:00",
    lastActivity: "2026-03-25T08:50:00",
    notes: "VOB denied — Tricare won't cover out-of-network residential",
    priority: "medium",
  },
  {
    id: "REF-3195",
    patientInitials: "N.W.",
    source: "Cooper University ER",
    sourceType: "er",
    bdo: "Marcus W.",
    stage: "vob_started",
    center: "Mays Landing",
    insurance: "Anthem",
    insuranceType: "commercial",
    createdAt: "2026-03-25T13:00:00",
    lastActivity: "2026-03-25T13:50:00",
    notes: "ER transfer — overdose recovery, needs detox",
    priority: "high",
  },
  {
    id: "REF-3194",
    patientInitials: "S.M.",
    source: "Drug Court — Camden County",
    sourceType: "court",
    bdo: "Derek S.",
    stage: "contacted",
    center: "Mays Landing",
    insurance: "Medicaid NJ",
    insuranceType: "medicaid",
    createdAt: "2026-03-25T10:00:00",
    lastActivity: "2026-03-25T11:30:00",
    notes: "Court-mandated — 72hr deadline for placement",
    priority: "high",
  },
  {
    id: "REF-3193",
    patientInitials: "B.T.",
    source: "988 Crisis Line",
    sourceType: "self",
    bdo: "",
    stage: "new",
    center: "",
    insurance: "Unknown",
    insuranceType: "self_pay",
    createdAt: "2026-03-25T14:10:00",
    lastActivity: "2026-03-25T14:10:00",
    notes: "988 warm transfer — active crisis, needs immediate callback",
    priority: "high",
  },
  {
    id: "REF-3192",
    patientInitials: "L.H.",
    source: "Family call-in",
    sourceType: "self",
    bdo: "",
    stage: "contacted",
    center: "Indianapolis",
    insurance: "Humana",
    insuranceType: "commercial",
    createdAt: "2026-03-25T08:45:00",
    lastActivity: "2026-03-25T09:30:00",
    notes: "Spouse called — patient willing but hesitant. Screening scheduled 3pm.",
    priority: "medium",
  },
];

// 14-day trend data for dashboard chart
export const timeSeries: TimeSeriesPoint[] = [
  { date: "Mar 12", inquiries: 92, vobStarted: 15, vobComplete: 6, admitted: 2 },
  { date: "Mar 13", inquiries: 105, vobStarted: 18, vobComplete: 8, admitted: 3 },
  { date: "Mar 14", inquiries: 88, vobStarted: 14, vobComplete: 5, admitted: 1 },
  { date: "Mar 15", inquiries: 78, vobStarted: 11, vobComplete: 5, admitted: 2 },
  { date: "Mar 16", inquiries: 65, vobStarted: 9, vobComplete: 4, admitted: 1 },
  { date: "Mar 17", inquiries: 110, vobStarted: 19, vobComplete: 9, admitted: 3 },
  { date: "Mar 18", inquiries: 98, vobStarted: 16, vobComplete: 7, admitted: 2 },
  { date: "Mar 19", inquiries: 102, vobStarted: 17, vobComplete: 8, admitted: 3 },
  { date: "Mar 20", inquiries: 95, vobStarted: 15, vobComplete: 6, admitted: 2 },
  { date: "Mar 21", inquiries: 112, vobStarted: 20, vobComplete: 9, admitted: 4 },
  { date: "Mar 22", inquiries: 70, vobStarted: 10, vobComplete: 4, admitted: 1 },
  { date: "Mar 23", inquiries: 62, vobStarted: 8, vobComplete: 3, admitted: 1 },
  { date: "Mar 24", inquiries: 108, vobStarted: 18, vobComplete: 8, admitted: 3 },
  { date: "Mar 25", inquiries: 55, vobStarted: 10, vobComplete: 4, admitted: 1 },
];
