import type { IntakeCase } from "./types";

// Jessica T.'s active case load
// Shows concurrent patients at different pipeline stages
export const intakeCases: IntakeCase[] = [
  {
    id: "CASE-001",
    patientInitials: "L.H.",
    age: 34,
    gender: "F",
    referralId: "REF-3192",
    referralSource: "Family call-in",
    sourceType: "self",
    assignedTo: "Jessica T.",
    stage: "intake_call",
    insurance: "Humana",
    insuranceType: "commercial",
    vobId: null,
    vobStatus: null,
    preAuthRequired: false,
    preAuthStatus: "not_needed",
    matchedCenterId: null,
    matchedCenterName: null,
    primarySubstance: "Alcohol",
    coOccurring: ["Depression"],
    urgency: "medium",
    createdAt: "2026-03-25T08:45:00",
    lastUpdated: "2026-03-25T09:30:00",
    stageEnteredAt: "2026-03-25T08:45:00",
    notes: "Spouse called — patient willing but hesitant. Screening scheduled 3pm today.",
    communications: [
      {
        id: "COM-001",
        timestamp: "2026-03-25T09:30:00",
        type: "call_in",
        to: "Spouse (caller)",
        summary: "Confirmed screening call for 3pm. Discussed what to expect during intake.",
      },
    ],
  },
  {
    id: "CASE-002",
    patientInitials: "M.R.",
    age: 28,
    gender: "M",
    referralId: "REF-3201",
    referralSource: "Jefferson Hospital ER",
    sourceType: "er",
    assignedTo: "Jessica T.",
    stage: "vob_processing",
    insurance: "Blue Cross Blue Shield",
    insuranceType: "commercial",
    vobId: "VOB-1847",
    vobStatus: "in_progress",
    preAuthRequired: true,
    preAuthStatus: "pending",
    matchedCenterId: null,
    matchedCenterName: null,
    primarySubstance: "Alcohol",
    coOccurring: ["Anxiety"],
    urgency: "high",
    createdAt: "2026-03-25T12:30:00",
    lastUpdated: "2026-03-25T13:15:00",
    stageEnteredAt: "2026-03-25T13:00:00",
    notes: "ER transfer request — patient medically stable, requesting detox bed. BDO Marcus W. involved.",
    communications: [
      {
        id: "COM-002",
        timestamp: "2026-03-25T13:15:00",
        type: "call_out",
        to: "BCBS Verification Line",
        summary: "Initiated VOB — waiting for benefits detail. Commercial PPO plan.",
      },
      {
        id: "COM-003",
        timestamp: "2026-03-25T12:45:00",
        type: "call_in",
        to: "Marcus W. (BDO)",
        summary: "BDO warm handoff. Jefferson ER has patient ready for transfer once bed confirmed.",
      },
    ],
  },
  {
    id: "CASE-003",
    patientInitials: "K.L.",
    age: 42,
    gender: "F",
    referralId: "REF-3200",
    referralSource: "Dr. Patel (PCP)",
    sourceType: "clinician",
    assignedTo: "Jessica T.",
    stage: "vob_processing",
    insurance: "Aetna",
    insuranceType: "commercial",
    vobId: "VOB-1846",
    vobStatus: "pending",
    preAuthRequired: false,
    preAuthStatus: "not_needed",
    matchedCenterId: null,
    matchedCenterName: null,
    primarySubstance: "Alcohol",
    coOccurring: [],
    urgency: "high",
    createdAt: "2026-03-25T11:00:00",
    lastUpdated: "2026-03-25T12:40:00",
    stageEnteredAt: "2026-03-25T12:00:00",
    notes: "PCP referral — alcohol use disorder, prior treatment 2024. Patient motivated.",
    communications: [
      {
        id: "COM-004",
        timestamp: "2026-03-25T12:40:00",
        type: "call_out",
        to: "Aetna Provider Services",
        summary: "Submitted VOB request. Plan has residential benefit — awaiting deductible info.",
      },
    ],
  },
  {
    id: "CASE-004",
    patientInitials: "T.J.",
    age: 31,
    gender: "M",
    referralId: "REF-3199",
    referralSource: "Website inquiry",
    sourceType: "self",
    assignedTo: "Jessica T.",
    stage: "vob_processing",
    insurance: "Medicaid PA",
    insuranceType: "medicaid",
    vobId: "VOB-1845",
    vobStatus: "needs_review",
    preAuthRequired: true,
    preAuthStatus: "pending",
    matchedCenterId: null,
    matchedCenterName: null,
    primarySubstance: "Opioid",
    coOccurring: ["PTSD"],
    urgency: "medium",
    createdAt: "2026-03-25T10:15:00",
    lastUpdated: "2026-03-25T11:20:00",
    stageEnteredAt: "2026-03-25T10:30:00",
    notes: "SLA BREACH — PA Medicaid requires ASAM 3.7 documentation. Complex pre-auth in progress.",
    communications: [
      {
        id: "COM-005",
        timestamp: "2026-03-25T11:20:00",
        type: "call_out",
        to: "PA Medicaid BH Line",
        summary: "Submitted pre-auth with ASAM documentation. Expected 24-48hr response.",
      },
      {
        id: "COM-006",
        timestamp: "2026-03-25T10:45:00",
        type: "call_out",
        to: "Patient T.J.",
        summary: "Informed about Medicaid pre-auth requirement. Patient understanding but anxious about wait.",
      },
    ],
  },
  {
    id: "CASE-005",
    patientInitials: "N.W.",
    age: 25,
    gender: "M",
    referralId: "REF-3195",
    referralSource: "Cooper University ER",
    sourceType: "er",
    assignedTo: "Jessica T.",
    stage: "pre_auth",
    insurance: "Anthem",
    insuranceType: "commercial",
    vobId: "VOB-1841",
    vobStatus: "verified",
    preAuthRequired: true,
    preAuthStatus: "approved",
    matchedCenterId: null,
    matchedCenterName: null,
    primarySubstance: "Opioid",
    coOccurring: ["Depression"],
    urgency: "high",
    createdAt: "2026-03-25T13:00:00",
    lastUpdated: "2026-03-25T14:30:00",
    stageEnteredAt: "2026-03-25T14:20:00",
    notes: "ER overdose recovery. VOB verified, pre-auth approved. Needs detox bed — checking Mays Landing.",
    communications: [
      {
        id: "COM-007",
        timestamp: "2026-03-25T14:30:00",
        type: "internal_note",
        to: "Admissions Team",
        summary: "Pre-auth approved by Anthem. Checking Mays Landing detox availability.",
      },
      {
        id: "COM-008",
        timestamp: "2026-03-25T14:00:00",
        type: "call_out",
        to: "Marcus W. (BDO)",
        summary: "Updated BDO on VOB verification and pre-auth approval. Ready for center match.",
      },
    ],
  },
  {
    id: "CASE-006",
    patientInitials: "C.B.",
    age: 38,
    gender: "F",
    referralId: "REF-3190",
    referralSource: "988 Crisis Warm Transfer",
    sourceType: "self",
    assignedTo: "Jessica T.",
    stage: "center_match",
    insurance: "Humana",
    insuranceType: "commercial",
    vobId: "VOB-1840",
    vobStatus: "verified",
    preAuthRequired: false,
    preAuthStatus: "not_needed",
    matchedCenterId: "IND",
    matchedCenterName: "Indianapolis",
    primarySubstance: "Benzodiazepine",
    coOccurring: ["Anxiety", "Insomnia"],
    urgency: "high",
    createdAt: "2026-03-24T22:15:00",
    lastUpdated: "2026-03-25T10:00:00",
    stageEnteredAt: "2026-03-25T09:30:00",
    notes: "988 warm transfer from last night. VOB cleared. Matched to Indianapolis — 3 beds available, accepts Humana.",
    communications: [
      {
        id: "COM-009",
        timestamp: "2026-03-25T10:00:00",
        type: "call_out",
        to: "Indianapolis Admissions",
        summary: "Confirmed bed availability and program fit. Residential PHP with benzo-specific protocol.",
      },
      {
        id: "COM-010",
        timestamp: "2026-03-25T09:00:00",
        type: "call_out",
        to: "Patient C.B.",
        summary: "Morning follow-up. Patient still willing to proceed. Discussed Indianapolis program.",
      },
    ],
  },
  {
    id: "CASE-007",
    patientInitials: "D.F.",
    age: 45,
    gender: "M",
    referralId: "REF-3188",
    referralSource: "Dr. Chen (Therapist)",
    sourceType: "therapist",
    assignedTo: "Jessica T.",
    stage: "transport_scheduled",
    insurance: "Cigna",
    insuranceType: "commercial",
    vobId: "VOB-1838",
    vobStatus: "verified",
    preAuthRequired: false,
    preAuthStatus: "not_needed",
    matchedCenterId: "EAR",
    matchedCenterName: "Earleville",
    primarySubstance: "Alcohol",
    coOccurring: [],
    urgency: "low",
    createdAt: "2026-03-24T09:00:00",
    lastUpdated: "2026-03-25T11:30:00",
    stageEnteredAt: "2026-03-25T11:00:00",
    notes: "Everything cleared. Transport arranged for tomorrow morning 8am to Earleville.",
    communications: [
      {
        id: "COM-011",
        timestamp: "2026-03-25T11:30:00",
        type: "call_out",
        to: "Transport Company",
        summary: "Confirmed medical transport for 3/26 at 8am. Pickup from patient home in Cherry Hill.",
      },
      {
        id: "COM-012",
        timestamp: "2026-03-25T11:00:00",
        type: "call_out",
        to: "Dr. Chen (Therapist)",
        summary: "Notified referring therapist of admission date. Dr. Chen will coordinate outpatient follow-up.",
      },
      {
        id: "COM-013",
        timestamp: "2026-03-25T10:30:00",
        type: "call_out",
        to: "Patient D.F.",
        summary: "Confirmed transport details and what to bring. Patient feels ready.",
      },
    ],
  },
  {
    id: "CASE-008",
    patientInitials: "A.P.",
    age: 29,
    gender: "F",
    referralId: "REF-3198",
    referralSource: "AtlantiCare Behavioral Health",
    sourceType: "clinician",
    assignedTo: "Jessica T.",
    stage: "admitted",
    insurance: "United Healthcare",
    insuranceType: "commercial",
    vobId: "VOB-1844",
    vobStatus: "verified",
    preAuthRequired: false,
    preAuthStatus: "not_needed",
    matchedCenterId: "DAN",
    matchedCenterName: "Danvers",
    primarySubstance: "Alcohol",
    coOccurring: ["Depression", "Anxiety"],
    urgency: "medium",
    createdAt: "2026-03-24T15:00:00",
    lastUpdated: "2026-03-25T10:22:00",
    stageEnteredAt: "2026-03-25T10:22:00",
    notes: "Admitted this morning at Danvers. Full journey complete: intake → VOB (37 min) → placement → transport → admitted.",
    communications: [
      {
        id: "COM-014",
        timestamp: "2026-03-25T10:22:00",
        type: "internal_note",
        to: "System",
        summary: "Patient admitted at Danvers. Treatment plan initiated.",
      },
      {
        id: "COM-015",
        timestamp: "2026-03-25T10:30:00",
        type: "email",
        to: "Lisa K. (BDO)",
        summary: "Notified BDO of successful admission. AtlantiCare referral — closed loop.",
      },
    ],
  },
];
