import type { ReferralSource, ActivityLogEntry } from "./types";

// Marcus W.'s personal referral source portfolio
// Distribution matches interview findings: ~60% ER, ~20% therapists, ~15% PCP, ~5% other
export const referralSources: ReferralSource[] = [
  {
    id: "SRC-001",
    name: "Jefferson Hospital ER",
    type: "er",
    facilityName: "Thomas Jefferson University Hospital",
    region: "northeast",
    tier: "platinum",
    healthScore: 72,
    referralsLast30: 14,
    referralsLast90: 51,
    conversionRate: 58,
    avgResponseHours: 1.2,
    lastContactDate: "2026-03-20T10:30:00",
    lastContactType: "visit",
    daysSinceContact: 5,
    nextScheduledVisit: "2026-03-27T09:00:00",
    volumeTrend: [5, 6, 4, 5, 3, 3, 2, 3],
    topInsurers: ["BCBS", "Medicaid PA", "Aetna"],
    preferredCenters: ["Philadelphia", "Devon"],
    notes: "Primary ER contact is Dr. Martinez (attending). Nurse coordinator Sarah rotating off next month — need to meet replacement.",
    alert: "Volume down 23% — schedule priority visit",
  },
  {
    id: "SRC-002",
    name: "Cooper University ER",
    type: "er",
    facilityName: "Cooper University Hospital",
    region: "northeast",
    tier: "gold",
    healthScore: 84,
    referralsLast30: 9,
    referralsLast90: 28,
    conversionRate: 64,
    avgResponseHours: 0.8,
    lastContactDate: "2026-03-23T14:00:00",
    lastContactType: "call",
    daysSinceContact: 2,
    nextScheduledVisit: "2026-03-28T11:00:00",
    volumeTrend: [3, 2, 3, 4, 3, 3, 3, 3],
    topInsurers: ["Anthem", "UHC", "BCBS"],
    preferredCenters: ["Mays Landing", "Philadelphia"],
    notes: "Strong relationship with charge nurse team. They appreciate same-day bed confirmations.",
    alert: null,
  },
  {
    id: "SRC-003",
    name: "AtlantiCare Behavioral Health",
    type: "er",
    facilityName: "AtlantiCare Regional Medical Center",
    region: "northeast",
    tier: "platinum",
    healthScore: 91,
    referralsLast30: 11,
    referralsLast90: 35,
    conversionRate: 71,
    avgResponseHours: 0.5,
    lastContactDate: "2026-03-24T09:00:00",
    lastContactType: "visit",
    daysSinceContact: 1,
    nextScheduledVisit: "2026-03-31T10:00:00",
    volumeTrend: [2, 3, 4, 4, 3, 4, 5, 4],
    topInsurers: ["BCBS", "Aetna", "UHC"],
    preferredCenters: ["Mays Landing", "Earleville"],
    notes: "Growing relationship. BH director invited us for grand rounds presentation in April.",
    alert: null,
  },
  {
    id: "SRC-004",
    name: "Camden Medical Center ER",
    type: "er",
    facilityName: "Camden Medical Center",
    region: "northeast",
    tier: "silver",
    healthScore: 61,
    referralsLast30: 4,
    referralsLast90: 14,
    conversionRate: 43,
    avgResponseHours: 2.1,
    lastContactDate: "2026-03-15T11:00:00",
    lastContactType: "visit",
    daysSinceContact: 10,
    nextScheduledVisit: null,
    volumeTrend: [2, 1, 2, 2, 1, 1, 2, 1],
    topInsurers: ["Medicaid NJ", "BCBS", "Anthem"],
    preferredCenters: ["Mays Landing"],
    notes: "High Medicaid mix makes conversion harder. New social worker started — need intro.",
    alert: "Overdue for check-in (10 days)",
  },
  {
    id: "SRC-005",
    name: "Shore Memorial ER",
    type: "er",
    facilityName: "Shore Medical Center",
    region: "northeast",
    tier: "bronze",
    healthScore: 38,
    referralsLast30: 1,
    referralsLast90: 3,
    conversionRate: 33,
    avgResponseHours: 4.5,
    lastContactDate: "2026-03-10T15:30:00",
    lastContactType: "email",
    daysSinceContact: 15,
    nextScheduledVisit: null,
    volumeTrend: [0, 1, 0, 0, 1, 0, 0, 1],
    topInsurers: ["BCBS", "Aetna"],
    preferredCenters: ["Mays Landing", "Earleville"],
    notes: "New source — only 3 referrals so far. ER director is interested but staff doesn't know our process yet.",
    alert: "New source — needs onboarding visit",
  },
  {
    id: "SRC-006",
    name: "Dr. Chen (Therapist)",
    type: "therapist",
    region: "northeast",
    tier: "gold",
    healthScore: 85,
    referralsLast30: 3,
    referralsLast90: 10,
    conversionRate: 80,
    avgResponseHours: 0.3,
    lastContactDate: "2026-03-22T16:00:00",
    lastContactType: "call",
    daysSinceContact: 3,
    nextScheduledVisit: null,
    volumeTrend: [1, 1, 1, 2, 1, 1, 1, 1],
    topInsurers: ["Cigna", "BCBS", "Aetna"],
    preferredCenters: ["Earleville", "Devon"],
    notes: "Excellent conversion rate — patients arrive pre-motivated. Prefers email updates on patient progress.",
    alert: null,
  },
  {
    id: "SRC-007",
    name: "Dr. Rivera (Therapist)",
    type: "therapist",
    region: "northeast",
    tier: "silver",
    healthScore: 68,
    referralsLast30: 2,
    referralsLast90: 5,
    conversionRate: 60,
    avgResponseHours: 1.5,
    lastContactDate: "2026-03-18T10:00:00",
    lastContactType: "email",
    daysSinceContact: 7,
    nextScheduledVisit: null,
    volumeTrend: [1, 0, 1, 1, 0, 1, 1, 0],
    topInsurers: ["UHC", "Aetna"],
    preferredCenters: ["Devon", "Philadelphia"],
    notes: "Dual-diagnosis specialist. Interested in our co-occurring disorders program at Devon.",
    alert: null,
  },
  {
    id: "SRC-008",
    name: "Dr. Patel (PCP)",
    type: "pcp",
    region: "northeast",
    tier: "silver",
    healthScore: 62,
    referralsLast30: 2,
    referralsLast90: 7,
    conversionRate: 71,
    avgResponseHours: 1.8,
    lastContactDate: "2026-03-12T14:00:00",
    lastContactType: "call",
    daysSinceContact: 13,
    nextScheduledVisit: null,
    volumeTrend: [1, 1, 0, 1, 1, 0, 1, 1],
    topInsurers: ["Aetna", "BCBS", "UHC"],
    preferredCenters: ["Devon", "Philadelphia"],
    notes: "Reliable low-volume source. High conversion — patients trust PCP recommendation. Wants quarterly outcome reports.",
    alert: "Overdue for check-in (13 days)",
  },
  {
    id: "SRC-009",
    name: "Camden County Drug Court",
    type: "court",
    region: "northeast",
    tier: "silver",
    healthScore: 55,
    referralsLast30: 2,
    referralsLast90: 8,
    conversionRate: 50,
    avgResponseHours: 3.2,
    lastContactDate: "2026-03-19T09:00:00",
    lastContactType: "visit",
    daysSinceContact: 6,
    nextScheduledVisit: "2026-04-02T09:00:00",
    volumeTrend: [1, 0, 1, 2, 1, 0, 1, 1],
    topInsurers: ["Medicaid NJ", "Self-pay"],
    preferredCenters: ["Mays Landing"],
    notes: "Court-mandated referrals have 72hr placement deadline. Medicaid mix and tight timelines make these challenging.",
    alert: null,
  },
];

// Recent outreach activity for Marcus W.
export const activityLog: ActivityLogEntry[] = [
  {
    id: "ACT-001",
    sourceId: "SRC-003",
    sourceName: "AtlantiCare Behavioral Health",
    type: "visit",
    date: "2026-03-24T09:00:00",
    notes: "Visited BH unit. Met with director Dr. Okonkwo — discussed grand rounds presentation for April.",
    outcome: "Agreed to present our outcomes data at April grand rounds",
  },
  {
    id: "ACT-002",
    sourceId: "SRC-002",
    sourceName: "Cooper University ER",
    type: "call",
    date: "2026-03-23T14:00:00",
    notes: "Follow-up call with charge nurse re: N.W. transfer. Confirmed bed availability at Mays Landing.",
    outcome: "Transfer coordinated for today",
  },
  {
    id: "ACT-003",
    sourceId: "SRC-006",
    sourceName: "Dr. Chen (Therapist)",
    type: "call",
    date: "2026-03-22T16:00:00",
    notes: "Provided update on R.S. admission at Earleville. Shared 30-day outcomes from previous patient.",
    outcome: "Dr. Chen pleased with outcomes — will refer next patient directly",
  },
  {
    id: "ACT-004",
    sourceId: "SRC-001",
    sourceName: "Jefferson Hospital ER",
    type: "visit",
    date: "2026-03-20T10:30:00",
    notes: "In-person visit to ER. Dr. Martinez flagged declining referrals — concerned about VOB delays losing patients.",
    outcome: "Committed to same-day VOB turnaround for Jefferson referrals",
  },
  {
    id: "ACT-005",
    sourceId: "SRC-009",
    sourceName: "Camden County Drug Court",
    type: "visit",
    date: "2026-03-19T09:00:00",
    notes: "Met with court liaison. Discussed 72hr placement requirement and Medicaid pre-auth process.",
    outcome: "Streamlined intake form for court referrals",
  },
  {
    id: "ACT-006",
    sourceId: "SRC-007",
    sourceName: "Dr. Rivera (Therapist)",
    type: "email",
    date: "2026-03-18T10:00:00",
    notes: "Sent dual-diagnosis program brochure for Devon center. Included patient testimonial.",
    outcome: "Waiting for response",
  },
];
